try 15

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -69,8 +69,12 @@ jobs:
       - name: Tag Docker Image
         if: ${{ github.ref == 'refs/heads/main' }}
         run: |
-          IMAGE_ID=$(docker images -q ${{ secrets.DOCKER_USERNAME }}/mark-api:latest)
-          docker tag $IMAGE_ID ${{ secrets.DOCKER_USERNAME }}/mark-api:latest
+          IMAGE_ID=$(docker images -q ${DOCKER_USERNAME}/mark-api:latest)
+          if [ -z "$IMAGE_ID" ]; then
+           echo "Error: Docker image ID not found. Build might have failed."
+           exit 1
+          fi
+          docker tag $IMAGE_ID ${DOCKER_USERNAME}/mark-api:latest
 
       - name: Docker Login
         if: ${{ github.ref == 'refs/heads/main' }}
